apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: todo-frontend
  name: todo-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: todo-frontend
        api: external        
    spec:
      containers:
      - image: galoomba12/todo:v1
        name: todo-frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always